name: Diary of a Geospatial Modelling Learner 
description: Blogging about geospatial data science and modelling
meta_description: "Hengshan's New Jekyll Site, Blogging about geospatial data science stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "" 
domain_name: "http://www.hengshanli.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Hengshan Li"

# Disqus config
disqus-shortname: ""
